name: "Podcast Generator"
author: "David Florez"
description: "Generates a feed for podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email:
    description: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}